# Setup packages

In [1]:
import pandas as pd
import numpy as np

# Dealing with the original data

The original dataset had many thousands of variables and was 1.2gb. Our first step was selecting the variables of interest from that dataset, putting them into a smaller dataframe, and exporting the dataframe with the few selected variables into a csv. Basically we were selecting a shortlist of variables with this step\
\
Here is the code that did that in markdown: \
\
    df = pd.read_stata('hsls_17_student_pets_sr_v1_0.dta') \
    vars_candidates = [
    
    "STU_ID",        # student ID

    # ---------- Outcome variables ----------
    "X5EVRDEF",      # ever defaulted on a federal loan (0/1)
    "X5OWEAMT",      # amount owed (principal + interest) on federal loans
    "X5PCTOWE",      # ratio owed / total borrowed (debt burden proxy)
    "X5T4XLNCUM",    # cumulative total federal loans (Title IV, no Parent PLUS)
    "X5PRIVLOANCUM", # cumulative private / alternative loans
    "X5PFYTOTFEDPRIV", # cumulative total federal + known private at primary first-year inst.

    # ---------- Loan / aid process ----------
    "X5EVRFEDAPP",   # ever applied for federal aid up to 2016
    "X5FEDAPP14",    # applied for federal aid 2013-14
    "X5FEDAPP15",    # applied for federal aid 2014-15
    "X5FEDAPP16",    # applied for federal aid 2015-16

    "S3APPFAFSA",    # family completed FAFSA for teen’s education
    "S3NODEBT",      # did not complete FAFSA because did not want debt
    "S3CANAFFORD",   # did not complete FAFSA because can afford without aid

    "S3CLGCOST",     # annual cost of chosen Nov 1, 2013 school (before aid)
    "S3CLGBORROW",   # amount borrowing for that school/year
    "S3CLGGRANT",    # grant/scholarship amount for that school/year

    "S3CLGSTAFFORD", # offered Stafford loan at Nov 1, 2013 school
    "S3CLGPELL",     # received Pell at Nov 1, 2013 school
    "S4PRVLOAN",     # any private student loan (yes/no)
    "S4PRVLOANEST",  # estimated range of private loan amount

    # ---------- Enrollment / attainment path ----------
    "X4EVRATNDCLG",  # ever attended any postsecondary institution after HS
    "X4ATPRLVLA",    # attainment + persistence at any institution (as of 2016)
    "X4ATPRTFI",     # attainment + retention at first institution
    "X4FB16ENRSTAT", # enrollment timing/status as of Feb 2016

    "X4REFDEGTYPE",  # type of reference degree (BA, AA, certificate, just classes)

    # ---------- Income / employment ----------
    "X4INCOMECAT",   # income category (overall)
    "S4EARNAMT2",    # earnings amount (self-reported)
    "S4EARNUNIT2",   # unit for S4EARNAMT2 (per hour / week / year etc.)
    "X3EARNPERHR1",  # hourly earnings on main job around 2013
    "X3EARNPERHR2",  # hourly earnings on other job

    # ---------- Major / program ----------
    "S3FIELD2",      # intended major (2-digit CIP) around 2013
    "S3FIELD_STEM",  # whether intended major is STEM
    "S4FIELD2",      # later major (2-digit CIP) by 2016 (if enrolled)
    "X3PROGLEVEL",   # degree program level (BA, AA, certificate, just taking classes)
    "S3PROGLEVEL",   # same idea but S3 version (non-imputed)

    # ---------- Institution characteristics ----------
    # Early “choice” institution in 2013
    "S3CLGSEL",      # IPEDS selectivity of enrolled college (2012 IC file)
    "S3CLGLVL",      # level: <2-year, 2-year, 4+ year
    "S3CLGCNTRL",    # control: public / private nonprofit / for-profit

    # Reference institution (where reference degree is pursued in 2016)
    "X4REFSECTOR",   # sector of reference institution
    "X4REFLEVEL",    # level of reference institution
    "X4REFCTRL",     # control of reference institution
    "X4REFSELECT",   # selectivity of reference institution

    # ---------- Baseline demographics & background ----------
    "X1SEX",         # student sex
    "X1RACE",        # race/ethnicity composite
    "X1HISPANIC",    # Hispanic/Latino indicator
    "X1FAMINCOME",   # total family income (2008)
    "X1POVERTY130",  # indicator relative to 130% of poverty threshold
    "X1SES",         # SES composite
    "X1SESQ5",       # SES quintile

    "X1PAREDU",      # parents’ highest education level
    "X1STUEDEXPCT",  # how far student expects to get in school (9th grade)
    "X1PAREDEXPCT",  # how far parent expects teen to go
    "X1TXMTH",       # baseline math theta (ability proxy)

    # ---------- High school / school context ----------
    "X1CONTROL",     # HS school control (public/private)
    "X1LOCALE",      # HS locale (urban / suburban / town / rural)
    "X1FREELUNCH",   # % free lunch at grade 9 (school SES context)
    "X1SCHBLACK",    # % of students who are Black
    "X1SCHHISP",     # % of students who are Hispanic
    "X1SCHWHITE",    # % of students who are White

    # ---------- Student plans & choice factors around 2013 ----------
    "S3WHERELIVE",   # where living while taking postsecondary classes
    "S3FOCUS",       # main focus (work, college, military, etc.) as of Nov 1, 2013
    "S3CLGFT",       # full-time / part-time enrollment
    "S3WORKFT",      # working full-time as of Nov 1, 2013

    "S3COSTATTEND",  # importance of cost of attendance in choosing school
    "S3JOBPLC",      # importance of job placement in choosing school
    "S3GRADSCHPLC",  # importance of grad-school placement
    "S3OFFERSFIELD", # importance of having a particular program of study

    # ---------- Data quality / linkage ----------
    "X5TRANRESP",    # postsecondary transcript response flag
    "X5SRRESP",      # student records response flag
    "W5PSRECORDS",    # postsecondary records analytic weight
    # Extra variables for salary / earnings analysis
    # 2013 hourly earnings (student’s own jobs)
    "X3EARNPERHR1",   # current job earnings per hour (2013 update)
    "X3EARNPERHR2",   # other job earnings per hour (2013 update)

    # 2016 income category (good for approximating annual income)
    "X4INCOMECAT",

    # Student expected earnings by education level (annualized)
    "X2S2EARNNOHS",   # expected earnings with <HS
    "X2S2EARNHS",     # expected earnings with HS only
    "X2S2EARNOCC",    # expected earnings with occupational/technical credential
    "X2S2EARN2YPUB",  # expected earnings with 2-year public college
    "X2S2EARN4Y",     # expected earnings with 4-year degree

    # Parent expected earnings by education level (annualized)
    "X2PEARNNOHS",
    "X2PEARNHS",
    "X2PEARNOCC",
    "X2PEARN2YPUB",
    "X2PEARN4Y",

    # Expected salary at age 30
    "S2OCC30EARN",    # expected earnings at age 30 (earlier wave)
    "S4OCC30EARN",    # expected yearly salary at age 30 (second follow-up)
]
\
    df[vars_candidates].to_csv('242A Project Data.csv', index=False)

    


# Data cleanup

After this initial selection of variables, we had to select the observations that were interesting for our analysis and clean up the data to facilitate modeling. \
We load the data. The original data had special codes with negative numbers for different types of missing data that for the purpose of our analysis we are just turning into NA. Then we restrict the observations used to just students that have taken out loans. \
Then we deal with encoding our target variables (default and high_debt_burden into binary variables): \
For default, we just encode whether the person defaulted on a loan or not into binaries. Simple enough. \
Then, for the high debt burden, first we had to populate a column with people's incomes, as that was not clearly delineated in the dataframe. Then we set a debt burden that is higher than 0.8 times the person's annual salary after graduation as a high debt burden. \
Lastly, we make a dataframe that has only our dependent variables and the independent variables that a student might know prior to taking out the loan (as the final tool is going to serve as advice before someone decides whether to take out the loan or not).

In [4]:
# -----------------------------
# 0. Load data
# -----------------------------
csv_path = "242A Project Data.csv"
df_raw = pd.read_csv(csv_path)

print("Initial shape:", df_raw.shape)

# Work on a copy
df = df_raw.copy()

FileNotFoundError: [Errno 2] No such file or directory: '242A Project Data.csv'

In [ ]:
# -----------------------------
# 1. Replace HSLS special codes
# -----------------------------
# Common numeric special codes for missing:
# -9, -8, -7, -4, -3, -2, -1
special_numeric = [-9, -8, -7, -4, -3, -2, -1]

numeric_cols = df.select_dtypes(include=["number"]).columns.tolist()
for col in numeric_cols:
    df[col] = df[col].replace(special_numeric, np.nan)

print("After replacing numeric special codes, shape:", df.shape)

After replacing numeric special codes, shape: (23503, 86)


In [ ]:
# -----------------------------
# 2. Restrict to borrowers
#    Borrowers: X5T4XLNCUM > 0 OR X5OWEAMT > 0
# -----------------------------
for col in ["X5T4XLNCUM", "X5OWEAMT"]:
    if col in df.columns:
        df[col] = pd.to_numeric(df[col], errors="coerce")

mask_list = []
if "X5T4XLNCUM" in df.columns:
    mask_list.append(df["X5T4XLNCUM"] > 0)
if "X5OWEAMT" in df.columns:
    mask_list.append(df["X5OWEAMT"] > 0)

if mask_list:
    borrower_mask = mask_list[0]
    for m in mask_list[1:]:
        borrower_mask |= m
else:
    # If both loan fields are missing, no borrowers can be identified
    borrower_mask = pd.Series(False, index=df.index)

df = df[borrower_mask].copy()
print("After restricting to borrowers, shape:", df.shape)

After restricting to borrowers, shape: (6729, 86)


In [ ]:
# -----------------------------
# 4. Build Target 1: default
#    Based on X5EVRDEF
#    default = 1 if "Defaulted"
#    default = 0 if "Did not default"
#    NaN otherwise
# -----------------------------
if "X5EVRDEF" in df.columns:
    def_map = {
        "Defaulted": 1,
        "Did not default": 0,
    }
    df["default"] = df["X5EVRDEF"].map(def_map)
else:
    df["default"] = np.nan

print("After creating default, value_counts:")
print(df["default"].value_counts(dropna=False))

After creating default, value_counts:
default
0    6552
1     177
Name: count, dtype: int64


In [ ]:
# -----------------------------
# 5. Build annual_earnings from S4EARNAMT2 / S4EARNUNIT2
#    and backfill using X3EARNPERHR1 / X3EARNPERHR2
# -----------------------------
df["annual_earnings"] = np.nan

# ----- 5a. Primary source: S4EARNAMT2 + S4EARNUNIT2 -----
if "S4EARNAMT2" in df.columns and "S4EARNUNIT2" in df.columns:
    # Coerce to numeric and drop HSLS negative codes (already done in step 1,
    # but this is defensive)
    earn_amt = pd.to_numeric(df["S4EARNAMT2"], errors="coerce")
    earn_amt = earn_amt.where(earn_amt >= 0, np.nan)

    # Treat very large reported values as missing
    earn_amt = earn_amt.where(earn_amt <= 1_000_000, np.nan)

    units = df["S4EARNUNIT2"]

    # Mapping from inspection:
    #   "per hour"  => hourly
    #   "per month" => monthly
    #   "per year"  => annual
    mask_hour  = units == "per hour"
    mask_month = units == "per month"
    mask_year  = units == "per year"

    annual = pd.Series(np.nan, index=df.index, dtype="float64")
    annual[mask_hour]  = earn_amt[mask_hour]  * 40 * 52
    annual[mask_month] = earn_amt[mask_month] * 12
    annual[mask_year]  = earn_amt[mask_year]

    df["annual_earnings"] = annual

# ----- 5b. Fallback: X3EARNPERHR1 / X3EARNPERHR2 (2013 hourly wages) -----
# Codebook: X3EARNPERHR1 = current job earnings per hour (2013 update),
#           X3EARNPERHR2 = other job earnings per hour. These are already
#           hourly, so just convert to annual using the same 40h*52w assumption.

has_x3 = False
for col in ["X3EARNPERHR1", "X3EARNPERHR2"]:
    if col in df.columns:
        has_x3 = True

if has_x3:
    # Clean negatives and convert to hourly
    h1 = pd.to_numeric(df["X3EARNPERHR1"], errors="coerce") if "X3EARNPERHR1" in df.columns else None
    h2 = pd.to_numeric(df["X3EARNPERHR2"], errors="coerce") if "X3EARNPERHR2" in df.columns else None

    if h1 is not None:
        h1 = h1.where(h1 >= 0, np.nan)
    if h2 is not None:
        h2 = h2.where(h2 >= 0, np.nan)

    # Annual earnings from X3:
    annual_x3 = pd.Series(np.nan, index=df.index, dtype="float64")

    if h1 is not None:
        annual_x3[~h1.isna()] = h1[~h1.isna()] * 40 * 52
    if h2 is not None:
        # For rows where we *still* don't have annual_x3 but do have h2:
        mask_fill_h2 = annual_x3.isna() & (~h2.isna())
        annual_x3[mask_fill_h2] = h2[mask_fill_h2] * 40 * 52

    # Only backfill where S4-based annual_earnings is still missing
    mask_backfill = df["annual_earnings"].isna() & (~annual_x3.isna())
    df.loc[mask_backfill, "annual_earnings"] = annual_x3[mask_backfill]

print("\nSummary of annual_earnings (describe()):")
print(df["annual_earnings"].describe())
print("\nProportion non-missing annual_earnings:", df["annual_earnings"].notna().mean())



Summary of annual_earnings (describe()):
count     5304.000000
mean     20342.066365
std       8271.246280
min       1000.000000
25%      16640.000000
50%      20000.000000
75%      22880.000000
max      62400.000000
Name: annual_earnings, dtype: float64

Proportion non-missing annual_earnings: 0.7882300490414623


In [ ]:
# -----------------------------
# 6. Build debt_to_income and Target 2: high_debt_burden
# -----------------------------
# debt_to_income = X5OWEAMT / annual_earnings
# only where both are positive and non-missing
if "X5OWEAMT" in df.columns:
    debt = pd.to_numeric(df["X5OWEAMT"], errors="coerce")
else:
    debt = pd.Series(np.nan, index=df.index, dtype="float64")

valid_dti_mask = (debt > 0) & (df["annual_earnings"] > 0)

dti = pd.Series(np.nan, index=df.index, dtype="float64")
dti[valid_dti_mask] = debt[valid_dti_mask] / df["annual_earnings"][valid_dti_mask]

df["debt_to_income"] = dti

print("\nSummary of debt_to_income (describe()):")
print(df["debt_to_income"].describe())

# high_debt_burden = 1 if dti > 0.8, 0 if dti <= 0.8, NaN otherwise
df["high_debt_burden"] = np.where(
    df["debt_to_income"] > 0.8,
    1,
    np.where(df["debt_to_income"].notna(), 0, np.nan),
)

print("\nhigh_debt_burden value_counts (dropna=False):")
print(df["high_debt_burden"].value_counts(dropna=False))


Summary of debt_to_income (describe()):
count    5215.000000
mean        1.059558
std         2.178073
min         0.009675
25%         0.318031
50%         0.664957
75%         1.063291
max        29.823000
Name: debt_to_income, dtype: float64

high_debt_burden value_counts (dropna=False):
high_debt_burden
0.0    3050
1.0    2165
NaN    1514
Name: count, dtype: int64


In [ ]:
# -----------------------------
# 7. Drop rows with missing targets
# -----------------------------
df = df[df["default"].notna() & df["high_debt_burden"].notna()].copy()
print("\nAfter dropping rows with missing targets, shape:", df.shape)

# Default and high debt burden rates
print("Default rate (mean of default):", df["default"].mean())
print("High debt burden rate (mean of high_debt_burden):", df["high_debt_burden"].mean())


After dropping rows with missing targets, shape: (5215, 90)
Default rate (mean of default): 0.022627037392138064
High debt burden rate (mean of high_debt_burden): 0.41514860977948226


In [ ]:
# -----------------------------
# 8. Build df_model with "known at enrollment" predictors
# -----------------------------
candidate_predictors = [
    # Baseline demographics & background
    "STU_ID",       # student ID
    "X1SEX",        # X1 student's sex
    "X1RACE",       # X1 student's race/ethnicity composite
    "X1HISPANIC",   # X1 indicator student is Hispanic/Latino
    "X1FAMINCOME",  # X1 family income category
    "X1POVERTY130", # X1 indicator family income <130% of poverty threshold
    "X1SES",        # X1 socioeconomic status composite
    "X1SESQ5",      # X1 SES quintile (1 lowest to 5 highest)
    "X1PAREDU",     # X1 highest education of either parent
    "X1STUEDEXPCT", # X1 student's own educational expectations
    "X1PAREDEXPCT", # X1 parent's educational expectations for student
    "X1CONTROL",    # X1 school control (public, Catholic, other private)
    "X1LOCALE",     # X1 school locale (city, suburb, town, rural)
    "X1FREELUNCH",  # X1 percent of 9th graders receiving free lunch
    "X1SCHBLACK",   # X1 percent of 9th graders who are Black/African American
    "X1SCHHISP",    # X1 percent of 9th graders who are Hispanic
    "X1SCHWHITE",   # X1 percent of 9th graders who are White

    # Intended major / program and early college characteristics
    "S3FIELD2",      # S3 intended major field (2 digit CIP)
    "S3FIELD_STEM",  # S3 intended major field is STEM indicator
    "S3PROGLEVEL",   # S3 level of program as of Nov 1 2013 (certificate, AA, BA etc.)
    "X3PROGLEVEL",   # X3 program level composite from 2013 update
    "S3CLGSEL",      # S3 selectivity of Nov 1 2013 institution
    "S3CLGLVL",      # S3 level of Nov 1 2013 institution (less than 2 year, 2 year, 4 year)
    "S3CLGCNTRL",    # S3 control of Nov 1 2013 institution (public vs private)
    "S3CLGSTAFFORD", # S3 offered federal Stafford loan for 2013 2014 at that school
    "S3CLGPELL",     # S3 offered Pell grant for 2013 2014 at that school

    # FAFSA / attitudes about debt
    "S3APPFAFSA",    # S3 completed a FAFSA for teenager's education
    "S3NODEBT",      # S3 reason for not filing FAFSA: did not want to go into debt
    "S3CANAFFORD",   # S3 reason for not filing FAFSA: can afford college without aid

    # Early student plans & focus
    "S3WHERELIVE",   # S3 where living while taking Nov 1 2013 postsecondary classes
    "S3FOCUS",       # S3 main focus as of Nov 1 2013 (school, work, family etc.)
    "S3CLGFT",       # S3 attending college full time as of Nov 1 2013
    "S3WORKFT",      # S3 working full time as of Nov 1 2013
    "S3COSTATTEND",  # S3 importance of cost of attendance in choosing Nov 1 2013 school
    "S3JOBPLC",      # S3 importance of job placement in choosing Nov 1 2013 school
    "S3GRADSCHPLC",  # S3 importance of graduate school placement in choosing Nov 1 2013 school
    "S3OFFERSFIELD", # S3 importance of school offering desired field of study
]


# Only keep predictors that actually exist in df
known_at_enrollment = [col for col in candidate_predictors if col in df.columns]

In [ ]:
# Map S3FIELD2 to broad intended-field groups
field_group_map = {
    # STEM-ish fields
    "Biological and Biomedical Sciences": "STEM",
    "Computer and Information Sciences and Support Services": "STEM",
    "Engineering": "STEM",
    "Engineering Technologies/Technicians": "STEM",
    "Mathematics and Statistics": "STEM",
    "Physical Sciences": "STEM",
    "Agriculture, Agriculture Operations, and Related Sciences": "STEM",
    "Natural Resources and Conservation": "STEM",
    "Architecture and Related Services": "STEM",

    # Health
    "Health Professions and Related Clinical Sciences": "Health",
    "Residency Programs": "Health",

    # Business
    "Business, Management, Marketing, and Related Support Services": "Business",

    # Education
    "Education": "Education",

    # Social sciences / policy / services
    "Social Sciences": "Social sciences",
    "Psychology": "Social sciences",
    "Public Administration and Social Service Professions": "Social sciences",
    "Security and Protective Services": "Social sciences",
    "Parks, Recreation, Leisure, and Fitness Studies": "Social sciences",
    "Legal Professions and Studies": "Social sciences",

    # Humanities & arts
    "English Language and Literature/Letters": "Humanities & arts",
    "Foreign languages, literatures, and Linguistics": "Humanities & arts",
    "History": "Humanities & arts",
    "Visual and Performing Arts": "Humanities & arts",
    "Communication, Journalism, and Related Programs": "Humanities & arts",

    # Liberal arts / interdisciplinary
    "Liberal Arts and Sciences, General Studies and Humanities": "Liberal arts",
    "Multi/Interdisciplinary Studies": "Liberal arts",

    # Applied / vocational
    "Family and Consumer Sciences/Human Sciences": "Other",
    "Construction Trades": "Trades",
    "Mechanic and Repair Technologies/Technicians": "Trades",
    "Precision Production": "Trades",
    "Personal and Culinary Services": "Trades",
    "Transportation and Materials Moving": "Trades",
    "Communications Technologies/Technicians and Support Services": "Trades",

    # Nonresponse / unknown
    "Don't know": "Undecided",
    "Unit non-response": "Undecided",
    "Item legitimate skip/NA": "Undecided",
    "Item not administered: abbreviated interview": "Undecided",
    "Uncodeable": "Undecided",
    "Missing": "Undecided",
}

# Start from S3FIELD2 text labels
df["intended_field_group"] = df["S3FIELD2"].map(field_group_map)

# If S3FIELD_STEM says "Yes", force into STEM (regardless of the text label)
if "S3FIELD_STEM" in df.columns:
    stem_mask = df["S3FIELD_STEM"] == "Yes"
    df.loc[stem_mask, "intended_field_group"] = "STEM"

# Anything still missing becomes Undecided / unknown
df["intended_field_group"] = df["intended_field_group"].fillna("Undecided")

# Quick sanity check
print(df["intended_field_group"].value_counts(dropna=False))


intended_field_group
Undecided            1216
STEM                 1039
Health                896
Business              560
Social sciences       557
Humanities & arts     370
Education             295
Trades                155
Liberal arts          121
Other                   6
Name: count, dtype: int64


In [ ]:
model_cols = ["default", "high_debt_burden", "intended_field_group"] + known_at_enrollment
df_model = df[model_cols].copy()

print("\nFinal df_model shape:", df_model.shape)
print("Columns in df_model:")
print(df_model.columns.tolist())


Final df_model shape: (5215, 40)
Columns in df_model:
['default', 'high_debt_burden', 'intended_field_group', 'STU_ID', 'X1SEX', 'X1RACE', 'X1HISPANIC', 'X1FAMINCOME', 'X1POVERTY130', 'X1SES', 'X1SESQ5', 'X1PAREDU', 'X1STUEDEXPCT', 'X1PAREDEXPCT', 'X1CONTROL', 'X1LOCALE', 'X1FREELUNCH', 'X1SCHBLACK', 'X1SCHHISP', 'X1SCHWHITE', 'S3FIELD2', 'S3FIELD_STEM', 'S3PROGLEVEL', 'X3PROGLEVEL', 'S3CLGSEL', 'S3CLGLVL', 'S3CLGCNTRL', 'S3CLGSTAFFORD', 'S3CLGPELL', 'S3APPFAFSA', 'S3NODEBT', 'S3CANAFFORD', 'S3WHERELIVE', 'S3FOCUS', 'S3CLGFT', 'S3WORKFT', 'S3COSTATTEND', 'S3JOBPLC', 'S3GRADSCHPLC', 'S3OFFERSFIELD']


In [ ]:
df_model.to_csv("242A_model_data.csv", index=False)

In [ ]:
# ============================================================
# TARGET 1 MODELING: DEFAULT (X5EVRDEF) — FINAL FIXED VERSION
# ============================================================

import pandas as pd
import numpy as np

from sklearn.model_selection import train_test_split
from sklearn.preprocessing import OneHotEncoder, StandardScaler
from sklearn.compose import ColumnTransformer
from sklearn.pipeline import Pipeline
from sklearn.impute import SimpleImputer

from sklearn.linear_model import LogisticRegression
from sklearn.discriminant_analysis import LinearDiscriminantAnalysis, QuadraticDiscriminantAnalysis
from sklearn.naive_bayes import GaussianNB
from sklearn.neighbors import KNeighborsClassifier
from sklearn.svm import SVC
from sklearn.tree import DecisionTreeClassifier
from sklearn.ensemble import RandomForestClassifier, GradientBoostingClassifier

from sklearn.metrics import (
    accuracy_score,
    roc_auc_score,
    f1_score,
    precision_score,
    recall_score,
    confusion_matrix,
)

# ============================================================
# 1. Load cleaned modeling data
# ============================================================
df = pd.read_csv("242A_model_data.csv")

target_col = "default"

cols_to_drop = ["default", "high_debt_burden", "STU_ID"]
feature_cols = [c for c in df.columns if c not in cols_to_drop]

X = df[feature_cols]
y = df[target_col].astype(int)

print("Shape of X:", X.shape)
print("Default rate:", y.mean())

# ============================================================
# 2. Train / Test Split (Stratified)
# ============================================================
X_train, X_test, y_train, y_test = train_test_split(
    X, y,
    test_size=0.2,
    random_state=42,
    stratify=y
)

# ============================================================
# 3. Preprocessing with IMPUTATION + SCALING + OHE
# ============================================================
cat_cols = X.select_dtypes(include=["object", "category"]).columns.tolist()
num_cols = [c for c in feature_cols if c not in cat_cols]

num_pipeline = Pipeline(
    steps=[
        ("imputer", SimpleImputer(strategy="median")),
        ("scaler", StandardScaler())
    ]
)

cat_pipeline = Pipeline(
    steps=[
        ("imputer", SimpleImputer(strategy="most_frequent")),
        ("encoder", OneHotEncoder(
            drop="first",
            handle_unknown="ignore",
            sparse_output=False
        )),
    ]
)

preprocess = ColumnTransformer(
    transformers=[
        ("num", num_pipeline, num_cols),
        ("cat", cat_pipeline, cat_cols),
    ]
)

# ============================================================
# 4. Define ALL MODELS
# ============================================================
models = {
    "Logit": LogisticRegression(max_iter=2000, class_weight="balanced"),
    "LDA": LinearDiscriminantAnalysis(),
    "QDA": QuadraticDiscriminantAnalysis(),
    "NaiveBayes": GaussianNB(),
    "kNN": KNeighborsClassifier(n_neighbors=15),
    "SVM": SVC(kernel="rbf", class_weight="balanced", probability=True),
    "DecisionTree": DecisionTreeClassifier(min_samples_leaf=5, class_weight="balanced"),
    "RandomForest": RandomForestClassifier(n_estimators=300, min_samples_leaf=5, class_weight="balanced", n_jobs=-1),
    "GradientBoosting": GradientBoostingClassifier(),
}

# ============================================================
# 5. BASELINE MODEL
# ============================================================
y_pred_baseline = np.zeros_like(y_test)
baseline_acc = accuracy_score(y_test, y_pred_baseline)
print("\n===== BASELINE MODEL =====")
print("Baseline Accuracy (always predict no default):", baseline_acc)

# ============================================================
# 6. TRAIN, PREDICT, EVALUATE
# ============================================================
results = []

for name, clf in models.items():
    print("\n==============================")
    print("Model:", name)
    print("==============================")

    pipe = Pipeline(
        steps=[
            ("preprocess", preprocess),
            ("clf", clf),
        ]
    )

    pipe.fit(X_train, y_train)

    y_pred = pipe.predict(X_test)

    if hasattr(clf, "predict_proba"):
        y_scores = pipe.predict_proba(X_test)[:, 1]
    else:
        y_scores = pipe.decision_function(X_test)

    acc = accuracy_score(y_test, y_pred)
    auc = roc_auc_score(y_test, y_scores)
    f1 = f1_score(y_test, y_pred)
    precision = precision_score(y_test, y_pred, zero_division=0)
    recall = recall_score(y_test, y_pred)

    print("Accuracy:", round(acc, 3))
    print("ROC AUC:", round(auc, 3))
    print("F1:", round(f1, 3))
    print("Precision:", round(precision, 3))
    print("Recall:", round(recall, 3))

    print("Confusion Matrix:")
    print(confusion_matrix(y_test, y_pred))

    results.append(
        {
            "model": name,
            "accuracy": acc,
            "auc": auc,
            "f1": f1,
            "precision": precision,
            "recall": recall,
        }
    )

# ============================================================
# 7. FINAL COMPARISON TABLE
# ============================================================
results_df = pd.DataFrame(results).sort_values(by="auc", ascending=False)

print("\n===== FINAL TARGET-1 MODEL COMPARISON =====")
print(results_df.to_string(index=False))


Shape of X: (5215, 37)
Default rate: 0.022627037392138064

===== BASELINE MODEL =====
Baseline Accuracy (always predict no default): 0.9769894534995206

Model: Logit
Accuracy: 0.778
ROC AUC: 0.645
F1: 0.065
Precision: 0.036
Recall: 0.333
Confusion Matrix:
[[803 216]
 [ 16   8]]

Model: LDA
Accuracy: 0.965
ROC AUC: 0.676
F1: 0.0
Precision: 0.0
Recall: 0.0
Confusion Matrix:
[[1006   13]
 [  24    0]]

Model: QDA


/opt/anaconda3/lib/python3.12/site-packages/sklearn/discriminant_analysis.py:947: UserWarning: Variables are collinear
  warnings.warn("Variables are collinear")


Accuracy: 0.977
ROC AUC: 0.5
F1: 0.0
Precision: 0.0
Recall: 0.0
Confusion Matrix:
[[1019    0]
 [  24    0]]

Model: NaiveBayes
Accuracy: 0.268
ROC AUC: 0.544
F1: 0.05
Precision: 0.026
Recall: 0.833
Confusion Matrix:
[[260 759]
 [  4  20]]

Model: kNN
Accuracy: 0.977
ROC AUC: 0.467
F1: 0.0
Precision: 0.0
Recall: 0.0
Confusion Matrix:
[[1019    0]
 [  24    0]]

Model: SVM
Accuracy: 0.958
ROC AUC: 0.626
F1: 0.043
Precision: 0.045
Recall: 0.042
Confusion Matrix:
[[998  21]
 [ 23   1]]

Model: DecisionTree
Accuracy: 0.895
ROC AUC: 0.522
F1: 0.052
Precision: 0.033
Recall: 0.125
Confusion Matrix:
[[931  88]
 [ 21   3]]

Model: RandomForest
Accuracy: 0.975
ROC AUC: 0.713
F1: 0.071
Precision: 0.25
Recall: 0.042
Confusion Matrix:
[[1016    3]
 [  23    1]]

Model: GradientBoosting
Accuracy: 0.972
ROC AUC: 0.697
F1: 0.0
Precision: 0.0
Recall: 0.0
Confusion Matrix:
[[1014    5]
 [  24    0]]

===== FINAL TARGET-1 MODEL COMPARISON =====
           model  accuracy      auc       f1  precision   re